Unattended-Upgrade::Allowed-Origins {
      // Install all updates.
      "${distro_id}:${distro_codename}-updates";
};

Unattended-Upgrade::Origins-Pattern {
      // Install Tailscale updates.
      "site=pkgs.tailscale.com,component=main";
      // Install Netdata updates.
      "site=repo.netdata.cloud";
      // Install all updates.
      // "origin=*";
};

Unattended-Upgrade::Mail "root";
